code style: replace astyle with clang-format
AStyle were causing intermittent and non-reproducible format on some
files and we ended deciding to move to clang-format as it seems more
stable.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

diff --git a/scripts/format-source-code b/scripts/format-source-code
--- a/scripts/format-source-code
+++ b/scripts/format-source-code
@@ -1,20 +1,72 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-if ! type astyle > /dev/null; then
-    cat <<EOF
-ERROR: The 'astyle' utility is not available in your machine.
+clang_format_executable=${CLANG_FORMAT_EXE:-clang-format}
 
-Please install it and run the script again. If you are running on a Debian based
-distribution you can run:
+this_program=$(basename "$0")
+usage="Usage:
+  $this_program [options] -- check format of the C++ source files
 
-$ apt install astyle
-EOF
-    exit 1
+Options:
+    -h --help         Print help and exit
+    -q --quiet        Quiet mode (do not print the diff)
+    -p --apply-patch  Apply diff patch to the source files"
+
+verbose=1
+apply_patch=0
+
+while [ $# -gt 0 ]; do
+  case $1 in
+  -p|--apply-patch)
+      apply_patch=1
+      ;;
+  -q|--quiet)
+      verbose=0
+      ;;
+  -h|--help)
+      echo "$usage"
+      exit 0
+      ;;
+  *)
+      echo "$this_program: Unknown argument '$1'. See '$this_program --help'."
+      exit -1
+      ;;
+  esac
+
+  shift
+done
+
+# stop right here if clang-format does not exist in $PATH
+command -v $clang_format_executable >/dev/null 2>&1 || { echo >&2 "clang-format executable '$clang_format_executable' not found.  Aborting."; exit 1; }
+
+# shamelessy redirecting everything to /dev/null in quiet mode
+if [ $verbose -eq 0 ]; then
+    exec &>/dev/null
 fi
 
-# We use the script path as a base and allow us to go to the source dir, so we
-# can run the script from there.
-sourcedir=$(dirname $0)/..
+source_files=$(git ls-files | grep -E "(\.hpp|\.cpp|\.h|\.c|\.java|\.m)$" | grep -E -v -f .clang-format-ignore)
 
-cd $sourcedir
-astyle --project=.astylerc --recursive '*.java' '*.cpp' '*.c' '*.h' '*.m'
+unformatted_files=()
+for file in $source_files; do
+    diff -u \
+        <(cat $file) \
+        --label a/$file \
+        <($clang_format_executable $file) \
+        --label b/$file >&1
+    if [ $? -eq 1 ]; then
+        unformatted_files+=($file)
+    fi
+done
+
+n_unformatted_files=${#unformatted_files[@]}
+if [ $n_unformatted_files -ne 0 ]; then
+    echo "${#unformatted_files[@]} file(s) not formatted properly:"
+    for file in ${unformatted_files[@]}; do
+        echo "    $file"
+        if [ $apply_patch -eq 1 ]; then
+            $clang_format_executable -i $file
+        fi
+    done
+else
+    echo "OK"
+fi
+exit $n_unformatted_files
